### PR TITLE
fixed ELCVCL and H2VCL efficiencies

### LINKED ISSUE #141: Fix ELCVCL and H2VCL efficiencies
PR #129 corrected the efficiencies of the ELCVCL and H2VCL technologies in the file ```09_uiuc.sql```.
However, PR #130 added the file ```10_uiuc.sql``` with the wrong efficiencies.
I guess this happened because I was working on both PRs simultaneously.

This issue can be closed when a PR updates the efficiencies in ```10_uiuc.sql```.
Luckily, ```11_uiuc.sql``` is fine because it was produced from ```09_uiuc.sql```.

### PR DESCRIPTION
**Pull request by robfairh**
Fixes #141

### CODE REVIEW

File: temoa-uiuc/data_files/10_uiuc.sql [hunk 1]
```diff
@@ -742,28 +742,28 @@ INSERT INTO "Efficiency" VALUES('uiuc', 'E85', 'E85VCL', 2028, 'UVCL', 0.734,'1
...
-INSERT INTO "Efficiency" VALUES('uiuc', 'H2', 'H2VCL', 2026, 'UVCL', 1.00,'1 kg h2 = 1.0 gal gsl');
-INSERT INTO "Efficiency" VALUES('uiuc', 'H2', 'H2VCL', 2027, 'UVCL', 1.00,'1 kg h2 = 1.0 gal gsl');
-INSERT INTO "Efficiency" VALUES('uiuc', 'H2', 'H2VCL', 2028, 'UVCL', 1.00,'1 kg h2 = 1.0 gal gsl');
-INSERT INTO "Efficiency" VALUES('uiuc', 'H2', 'H2VCL', 2029, 'UVCL', 1.00,'1 kg h2 = 1.0 gal gsl');
-INSERT INTO "Efficiency" VALUES('uiuc', 'H2', 'H2VCL', 2030, 'UVCL', 1.00,'1 kg h2 = 1.0 gal gsl');
+INSERT INTO "Efficiency" VALUES('uiuc', 'H2', 'H2VCL', 2021, 'UVCL', 2.40,'1 kg h2 = 2.4 gal gsl');
+INSERT INTO "Efficiency" VALUES('uiuc', 'H2', 'H2VCL', 2022, 'UVCL', 2.40,'1 kg h2 = 2.4 gal gsl');
+INSERT INTO "Efficiency" VALUES('uiuc', 'H2', 'H2VCL', 2023, 'UVCL', 2.40,'1 kg h2 = 2.4 gal gsl');
+INSERT INTO "Efficiency" VALUES('uiuc', 'H2', 'H2VCL', 2024, 'UVCL', 2.40,'1 kg h2 = 2.4 gal gsl');
+INSERT INTO "Efficiency" VALUES('uiuc', 'H2', 'H2VCL', 2025, 'UVCL', 2.40,'1 kg h2 = 2.4 gal gsl');
```
Comment (samgdotson) [inline temoa-uiuc/data_files/10_uiuc.sql:761]: We've discussed this before, but just to be clear: The energy content of 1kg H2 = 1 gallon gsl but the conversion from potential to kinetic energy is more efficient for H2 vehicles than gasoline vehicles, right?

Comment (robfairh) [reply temoa-uiuc/data_files/10_uiuc.sql:761]: Correct. Another way to see it is using the mileage per gallon. 1 gallon of gasoline (in a conventional vehicle) yields X miles, and 1 kg of hydrogen (in an FCEV) yields Y miles. Y being greater than X (I am using X and Y cause I don't remember the numbers from the top of my head, but you get the idea).

**Review by samgdotson — APPROVED** [review]
backwards compatibility
